# This is the configuration for the Agriculture demonstration scenario
application-scenario-config:
  fclRulesFilePath: rules/AgricultureSchedulingSlidingDecisionRules.fcl
  decisionResultsDescription:
    droneShouldCarryTheBox: "Let the drone carry the box"
    letHumanDecide : "Let the worker decide"
    humanShouldCarryTheBox: "Let the worker carry the box"
    # Quote is used because YAML parsers can interpret these values as booleans rather than text keys
    "yes": "Inform the supervisor"
    "no": "Do not inform the supervisor"
