# This file defines Logistics pilot configurations for the application.
# To activate this profile use command 'mvn spring-boot:run -D"spring-boot.run.profiles"=construction'
application-scenario-config:
  fclRulesFilePath: rules/ConstructionRobotAssistanceDecisionRules.fcl
  decisionResultsDescription:
    ROBOT_AUTONOMOUSLY: "Let the robot continue trying"
    HUMAN_ON_THE_LOOP: "Inform human about the problem"
    HUMAN_IN_THE_LOOP: "Warn human, but let them decide if/when to help"
    HUMAN_REQUIRED: "Ask human for help"
    AUTONOMOUS: "system is currently operating autonomously"
    SEMI_AUTONOMOUS: "system currently operating semi-autonomously"
    MANUAL: "system currently operating manually"
