import eu.ai4work.sws.model.specific.CongestionLevel;
import eu.ai4work.sws.model.specific.TruckPosition;
import eu.ai4work.sws.model.generic.SlidingDecisionResult;

rule "AI can reschedule without human involvement"
when
    $noOfTrucksInQueue : CongestionLevel( this == CongestionLevel.LOW )
then
    insert(SlidingDecisionResult.AI_AUTONOMOUSLY);
end

rule "Human has to be informed about AI's rescheduling"
when
    $noOfTrucksInQueue : CongestionLevel( this == CongestionLevel.MEDIUM )
    $positionOfTruck : TruckPosition( this == TruckPosition.NEAR_THE_FRONT_OF_THE_QUEUE )
then
    insert(SlidingDecisionResult.HUMAN_ON_THE_LOOP);
end

rule "Human has to check AI's suggestion"
when
    ($noOfTrucksInQueue : CongestionLevel( this == CongestionLevel.MEDIUM ) &&
     $positionOfTruck : TruckPosition( this == TruckPosition.IN_THE_BACK_OF_THE_QUEUE )) ||
    ($noOfTrucksInQueue : CongestionLevel( this == CongestionLevel.HIGH ) &&
     $positionOfTruck : TruckPosition( this == TruckPosition.NEAR_THE_FRONT_OF_THE_QUEUE ))
then
    insert(SlidingDecisionResult.HUMAN_IN_THE_LOOP);
end

rule "Human has to decide without support"
when
    $noOfTrucksInQueue : CongestionLevel( this == CongestionLevel.HIGH )
    $positionOfTruck : TruckPosition( this == TruckPosition.IN_THE_BACK_OF_THE_QUEUE )
then
    insert(SlidingDecisionResult.HUMAN_MANUALLY);
end
