name: Java CI with Maven and Release Artifact

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5.7.0
        with:
          java-version: '25.0.3'
          distribution: 'temurin'
          cache: maven

      - name: Set version from tag
        if: github.event_name == 'release'
        run: |
          TAG_NAME="${{ github.ref_name }}"
          mvn versions:set -DnewVersion="${TAG_NAME#v}" -DprocessAllModules

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to registry
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.actor }}" --password-stdin

      - name: Build and push the container image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_VERSION="${{ github.event_name == 'release' && github.ref_name || 'latest' }}"
          IMAGE_VERSION="${IMAGE_VERSION#v}"

          docker buildx build \
            --push \
            --file ./Dockerfile \
            --tag "${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}:${IMAGE_VERSION}" \
            .

      - name: Upload release JAR
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: target/sliding-work-sharing-*.jar
